apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # <--- replace with your AWS region
      # Authentication options:
      # 1) Recommended in EKS: use IRSA / IAM role for serviceAccount and set auth.jwt.serviceAccountRef below
      # 2) For other clusters, create a kube secret with AWS keys and reference it via secretRef
      # Example (secretRef):
      # auth:
      #   secretRef:
      #     accessKeyIDSecretRef:
      #       name: aws-credentials
      #       namespace: external-secrets
      #       key: accessKeyID
      #     secretAccessKeySecretRef:
      #       name: aws-credentials
      #       namespace: external-secrets
      #       key: secretAccessKey
      
      auth:
        # Uncomment and use one of the auth methods below according to your environment.
        # jwt:
        #   serviceAccountRef:
        #   name: external-secrets-sa
        #   namespace: external-secrets
        # secretRef:
        #   accessKeyIDSecretRef:
        #     name: aws-credentials
        #     namespace: external-secrets
        #     key: accessKeyID
        #   secretAccessKeySecretRef:
        #     name: aws-credentials
        #     namespace: external-secrets
        #     key: secretAccessKey
